// The Hustle: the self-test. Loaded only when the page is opened with ?test=1; it never touches your real save.
function selfTest(){ // open with ?test=1 — never touches your real save
  wiped=true;const ok=(c,m)=>{if(!c)throw Error(m)};
  ok(fmt(1234)==='$1.23K','fmt K');ok(fmt(12.5)==='$12.50','fmt cents');ok(fmt(-2e6)==='-$2.00M','fmt neg');ok(bmul(25)===2.25,'milestones');
  ok(Math.abs(bcost(BIZ[0],0,2)-(120+120*1.25))<1e-6,'bcost sum');
  newGame('Test','street');s.cash=1e7;ACT.bbuy('lemon','max');ok(s.biz.lemon.n>=25&&bmax(BIZ[0],s.biz.lemon.n)===0,'buy max spends down');
  s.cash=1e6;ACT.buy('NOVA','10');ACT.sell('NOVA','all');ok(!s.port.NOVA,'sell all');
  s.cash=2e5;s.job='crew';relist();s.re.list[0]={...s.re.list[0],t:'studio'};const lu=s.re.list[0].uid;ACT.pbuy(lu,'m');
  const hp=homeP();ok(hp&&hp.loan>0&&s.home===hp.uid,'mortgage buy moves you in');const l0=hp.loan;for(let i=0;i<365;i++)day();ok(P(hp.uid).loan<l0,'mortgage amortises');
  s.cash=2e7;ACT.cbuy('hatch');ACT.cbuy('classic');const h0=s.cars[0].v;for(let i=0;i<365;i++)day();ok(s.cars[0].v<h0,'cars depreciate');
  ACT.live(hp.uid);ACT.moveout(hp.uid);ok(!s.home,'move out');ACT.psell(hp.uid);ok(!s.props.length,'sell property');
  let tot=0;for(let i=0;i<200000;i++)tot+=slotSpin().m;const rtp=tot/2e5;ok(rtp>.86&&rtp<.97,'slots RTP '+rtp.toFixed(3));
  ok(rlMult('red',1)===2&&rlMult('red',0)===0&&rlMult('black',1)===0&&rlMult('n17',17)===36&&rlMult('n17',18)===0&&rlMult('d2',13)===3&&rlMult('low',18)===2,'roulette payouts');
  ok(hv([4,52])===21&&hv([4,5,36])===21&&hv([40,44,48])===30&&hv([4,20])===16,'hand values');
  s.cash=1e7;s.cz.chip=100;const c0=s.cash;for(let i=0;i<3000;i++){ACT.deal();while(!s.cz.bj.done)hv(s.cz.bj.p)<17?ACT.hit():ACT.stand()}
  const edge=(s.cash-c0)/3e5;ok(s.cz.played===3000&&edge>-.15&&edge<.08,'blackjack edge '+edge.toFixed(3));
  s.cash=1e5;ACT.xbuy('SATS','10000');const u0=s.wallet.SATS.u;ok(u0>0&&s.cash===9e4,'crypto buy');ACT.xsell('SATS','.5');ok(Math.abs(s.wallet.SATS.u-u0/2)<1e-12,'crypto sell half');
  s.cash=5e9;relist();ACT.pbuy(s.re.list[0].uid);ACT.pbuy(s.re.list[1].uid);s.props.at(-1).from=0;s.home=s.props[0].uid;ok(s.props.length===2,'two properties');s.cash=5e6;
  for(let i=0;i<1500;i++)cryptoDay();ok(s.cx.launched>0,'meme coins launch');ACT.xbuy(s.cx.coins[0].t,'1000');
  s.people=[];makeFamily();ok(s.people.filter(p=>p.role==='parent').length===2,'family made');
  const dt=meet('date',100);dt.met=-1000;s.cash=1e11;for(let i=0;i<30&&dt.role==='date';i++){dt.rel=100;ACT.pp(dt.uid,'propose')}ok(dt.role==='spouse','propose');
  for(let i=0;i<30&&!kids().length;i++){dt.c.baby=0;dt.rel=100;ACT.pp(dt.uid,'baby')}ok(kids().length===1,'baby');
  const r0=dt.rel;for(let i=0;i<100;i++)peopleDay();ok(dt.rel<r0,'relationships fade');
  ACT.pp(dt.uid,'divorce');ok(dt.role==='spouse'&&!$('#modal').hidden,'divorce asks first');ACT.pp(dt.uid,'divorce!');ok(dt.role==='ex'&&$('#modal').hidden,'divorce');
  ok(jobMiss(JM.surgeon).length&&canJob(JM.crew),'job requirements');s.job=null;ACT.apply('crew');ok(iv&&!$('#modal').hidden,'interview opens');ACT.answer('exp');ok(s.job==='crew'||s.cd.job_crew>s.day,'interview resolves');
  s.job='crew';s.perf=40;ACT.work('hard');ok(s.perf===40+(boss()?.bt==='micro'?7:5),'work hard');
  s.study=null;s.st.sma=90;s.cash=1e7;ACT.learn('ba');ok(enr&&!$('#modal').hidden,'enroll opens');ACT.mj('Nursing');ACT.enroll('online','cash');ok(s.study?.mj==='Nursing','enrolled');
  s.study.g=90;for(let i=0;i<2000&&s.study;i++)day();ok(s.degs.some(d=>d.p==='ba'&&d.mj==='Nursing')&&s.edu>=2&&canJob(JM.nurse),'graduated as nurse');
  s.cash=0;s.debt=0;ACT.learn('ma');ACT.enroll('online','loan');ok(s.study&&s.debt>0,'student loan');const d0=s.debt;for(let i=0;i<30;i++)day();ok(s.debt<d0,'loan repays');
  ok(xpY('health')>=1,'major counts as experience');tab='school';VIEWS.school();
  s.tour=0;ACT.guide();ok(tour===0&&speed===0,'guide starts paused');for(let i=0;i<TOUR.length;i++)ACT.tnext();ok(tour===-1&&s.tour===1&&speed>0,'guide finishes');
  const sp=meet('spouse',60),ex=meet('ex',20),kd=addChild();kd.b=s.day-8*365;meet('friend',60);(s.people.find(p=>p.role==='parent')||meet('parent',60)).b=s.day-66*365;s.inbox=[];for(const q of s.props)if(q.uid!==s.home)q.from=0;for(const p of s.people)if(p.role==='friend')p.rel=60;
  const base=JSON.stringify({...s,job:'swe',fol:20000,cash:2e6,biz:{truck:{n:12,mgr:0,pend:0,spent:1e5},cafe:{n:3,mgr:1,pend:0,spent:1e5}},port:{NOVA:{sh:50,cost:5000}}});
  for(const e of EV)for(const[,fx]of e.ch){s=JSON.parse(base);s.st.hap=10;const m=fx(s,e.a?e.a(s):0);ok(typeof m==='string','event '+e.id)}
  for(const k in POSTS){s=JSON.parse(base);ACT.post(k)}
  for(const k in VIEWS){tab=k;VIEWS[k]()}ok(railHtml().includes('Markets')&&barHtml().includes('Money')&&typeof subtabs()==='string','navigation');
  s.inbox=[{id:'lotto',d:s.day,a:0}];ok(needs().some(n=>n.k==='dec'),'decision shows in needs');ACT.pick('lotto','1');ok(!s.inbox.length,'inline decision');
  ok(plural('Car Wash')==='Car Washes'&&plural('Rocket Company')==='Rocket Companies'&&plural('Food Truck')==='Food Trucks','plurals');
  bmode='10';tab='biz';VIEWS.biz();bmode='1';for(const g of GAMES){cg=g.id;VIEWS.casino()}cg=null;
  s.day=nextTrading(s.day);s.min=600;s.cash=1e6;sel='NOVA';ot={side:'buy',qty:7};const n0=s.port.NOVA?.sh||0;ACT.order();ok(s.port.NOVA.sh===n0+7,'order ticket buys');ot.side='sell';ot.qty=3;ACT.order();ok(s.port.NOVA.sh===n0+4,'order ticket sells');ot={side:'buy',qty:10};
  s.cz.chip=100;for(let i=0;i<20000;i++){ACT.dice(['under','over','seven'][i%3]);ACT.flip(i%2?'h':'t')}const dg=s.cz.g.dice,cf=s.cz.g.coin;
  ok(dg.n===20000&&cf.n===20000&&dg.net/2e6>-.08&&dg.net/2e6<.02&&cf.net/2e6>-.05&&cf.net/2e6<.01,'dice and coin edges');
  newGame('Old','street');delete s.re;delete s.cx;delete s.cz;delete s.people;delete s.degs;s.edu=2;s.study={lvl:3,left:50};s.rel=2;s.kids=2;s.own={apt:1,car:1,bike:1};s.port.MOON={sh:10,cost:12};upgrade();ok(partner()?.role==='spouse'&&kids().length===2&&!('rel' in s),'old relationships upgrade');ok(s.degs.length===2&&s.study.p==='ma','old education upgrade');ok(s.props.length===1&&s.cars.length===1&&s.own.bike&&homeP()&&s.wallet.MOON.u===10&&!s.port.MOON&&s.cz,'old saves upgrade');
  newGame('Clock','street');delete s.min;for(const k of STOCKS){const x=s.px[k.t];delete x.k;delete x.op}upgrade();ok(s.min===480&&s.px.NOVA.k.length===s.px.NOVA.h.length&&s.px.NOVA.op>0,'old saves get a clock and candles');tab='stock';VIEWS.stock();
  const q=s.px.NOVA,pc=q.h.at(-1),mk=q.k.at(-1);ok(s.day%7===0&&s.min===480&&!mktOpen(),'Monday 8 AM, market shut');
  s.cash=1e6;s.min=500;ot={side:'buy',qty:5};ACT.order();ok(!s.port.NOVA,'no trading while closed');
  s.min=480;for(let i=0;i<91;i++)minute();ok(mktOpen()&&Math.abs(q.o/pc-1)<1e-5&&q.k.at(-1)[0]===q.op&&q.k.at(-2)===mk,'the bell opens a new session');
  for(let i=0;i<400;i++)minute();const c=q.p;ok(!mktOpen()&&q.h.at(-1)===c&&q.hi>=Math.max(q.op,c)&&q.lo<=Math.min(q.op,c),'the session closes with its high and low');
  for(let i=0;i<600;i++)minute();ok(q.p===c&&s.day===1,'prices hold overnight');
  const d7=s.day;for(let i=0;i<7*1440;i++)minute();let ns=1;for(let d=d7;d<s.day;d++)ns+=tradingDay(d)&&d>0?1:0;ok(holiday(7)==='Martin Luther King Jr. Day'&&q.k.length-1-q.k.indexOf(mk)===ns,'sessions skip weekends and holidays');
  const sd=a=>{const r=[];for(let i=1;i<a.length;i++)r.push(Math.abs(Math.log(a[i]/a[i-1])));return r.sort((x,y)=>x-y)[r.length>>1]};
  const cb0=closeBell;closeBell=()=>{s.mkt.ic=idx()};s.mkt.bull=true;s.mkt.h=MVOL.bull**2/YR; // hold volatility still so both samples see the same market
  let lv=0,bk=0;for(const k of MAIN){const x=s.px[k.t];x.p=k.p;x.h=[k.p];x.k=[[k.p,k.p,k.p]]}for(let i=0;i<1440*7*26;i++)minute();for(const k of MAIN)lv+=sd(s.px[k.t].h);
  for(const k of MAIN){const x=s.px[k.t];x.h=[k.p];x.k=[[k.p,k.p,k.p]]}for(let i=0;i<130;i++)tradeDay(1);for(const k of MAIN)bk+=sd(s.px[k.t].h);
  closeBell=cb0;ok(lv/bk>.75&&lv/bk<1.33,'live sessions move like whole-day steps '+(lv/bk).toFixed(2));
  delete s.px.NVBA;delete s.px.CBAS;upgrade();ok(s.px.NVBA.h.length===240&&s.px.CBAS.k.length===240&&Number.isFinite(s.px.NVBA.p),'new stocks seed into old saves');ok(Math.abs(s.px.NVBA.p/SK.NVBA.p-1)<1e-9,'history ends at the listed price');
  tab='stock';wf='Semis';ok(VIEWS.stock().includes('NVBA')&&!VIEWS.stock().includes('>MSFY<'),'sector filter');wf='Held';VIEWS.stock();wf='All';
  newGame('Coins','street');const sats=coin('SATS'),usd=s.cx.coins.find(c=>c.stable);s.day=5;s.min=120;const cp=sats.p;for(let i=0;i<30;i++)minute();ok(sats.p!==cp&&sats.h.at(-1)===sats.p&&usd.p===1,'crypto trades at 2 AM on a Saturday');
  const fixed=()=>s.cx.coins.filter(c=>!c.meme&&!c.stable),cs=()=>fixed().reduce((a,c)=>a+sd(c.h),0),reset=()=>{for(const c of s.cx.coins){c.h=[c.p];c.fd=0}};
  reset();for(let i=0;i<1440*140;i++)minute();const cl=cs();reset();for(let i=0;i<140;i++){s.day++;cryptoDay(1)}const cb=cs();ok(cl/cb>.75&&cl/cb<1.33,'live crypto moves like whole-day steps '+(cl/cb).toFixed(2));
  newGame('Own','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e12;ok(PENNIES.length>=50,'50 penny stocks');
  ok(STOCKS.every(k=>{const f=fund(k);return [f.rev,f.ni,f.emp,f.ps,f.eps].every(Number.isFinite)&&f.rev>0&&f.emp>=3}),'company data');
  const pk=PENNIES.find(k=>k.pe>0)||PENNIES[0],pp=s.px[pk.t].p;ACT.buy(pk.t,Math.floor(pk.sh*.1));ok(s.px[pk.t].p>pp*1.05,'big buys push the price up');
  ACT.ctrl(pk.t);ok(controls(pk.t),'buying a controlling stake');checkGoals();ok(s.goals.tycoon,'tycoon goal');ok(pk.pe===0||flows().own>0,'control pays profits');
  const c1=s.cash,p1=s.px[pk.t].p;ACT.sdiv(pk.t);ok(s.cash>c1&&s.px[pk.t].p<p1,'special dividend');ACT.grow(pk.t);ok(s.px[pk.t].gr>s.day,'growth push');
  sel=pk.t;ACT.rename(pk.t);$('#cname').value='<b>Evil</b> Co';ACT.rename2(pk.t);ok(nameOf(pk.t)==='<b>Evil</b> Co'&&!VIEWS.stock().includes('<b>Evil</b>'),'renames are escaped');
  const c2=s.cash;ACT.sell(pk.t,'all');ok(!s.port[pk.t]&&!controls(pk.t)&&s.cash>c2,'sell out and lose control');
  const i0=idxDay();s.px[pk.t].p*=100;ok(idxDay()===i0,'penny stocks stay out of the index');
  const bz=PENNIES[1];ACT.buy(bz.t,100);s.px[bz.t].p=.001;marketDay();ok(!s.port[bz.t]&&s.px[bz.t].p>=.2&&nameOf(bz.t)!==bz.n&&s.px[bz.t].h.length===1,'bankrupt penny relists');sel=bz.t;VIEWS.stock();sel='NOVA';
  ok(dateOf(0).m===0&&dateOf(0).dd===8&&dateOf(0).wd===0,'day 0 is Monday, January 8');
  for(let y=1;y<=8;y++){const H=holidays(y).H,ks=Object.keys(H).map(Number),tg=ks.find(d=>H[d]==='Thanksgiving');ok(ks.length>=8&&ks.length<=9&&wdOf(tg)===3&&dateOf(tg).m===10&&ks.every(d=>wdOf(d)<5),'holidays in year '+y)}
  newGame('Real','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e6;const pz=PENNIES[2],[b0,a0]=bidAsk(pz.t);ok(a0>b0,'bid below ask');const cz=s.cash;ACT.buy(pz.t,100);ACT.sell(pz.t,'all');ok(s.cash<cz,'a round trip pays the spread');
  const nv=s.px.NVBA;sel='NVBA';s.orders=[];ot={side:'buy',qty:10,type:'limit',px:+(nv.p*1.2).toPrecision(4),tif:'day'};ACT.order();ok(s.orders.length===1,'limit order placed');minute();ok(!s.orders.length&&s.port.NVBA?.sh===10,'a marketable limit fills');
  ot={side:'sell',qty:10,type:'stop',px:+(nv.p*.5).toPrecision(4),tif:'gtc'};ACT.order();ot={side:'buy',qty:5,type:'limit',px:+(nv.p*.5).toPrecision(4),tif:'day'};ACT.order();ok(s.orders.length===2,'resting orders');
  s.min=closeAt()-1;minute();ok(s.orders.length===1&&s.orders[0].tif==='gtc','day orders expire at the close');
  shock('NVBA',-.6,true);s.day=nextTrading(s.day+1);s.min=600;fillOrders();ok(!s.orders.length&&!s.port.NVBA,'a stop sell triggers');ot={side:'buy',qty:10,type:'market'};
  s.mkt.ic=idx();s.mkt.cb=0;s.mkt.hd=-1;for(const k of MAIN)shock(k.t,-.25,true);s.mkt.rc*=.75;breakers();ok(halted()&&!mktOpen()&&s.mkt.cb===3,'a 20% plunge closes the market');s.mkt.hd=-1;
  const sq=s.px.CSTK,sh0=shOf('CSTK');s.port.CSTK={sh:10,cost:1e4};sq.p=2600;split(SK.CSTK);ok(shOf('CSTK')===sh0*10&&s.port.CSTK.sh===100&&Math.abs(100*sq.p-26000)<1e-6,'a split keeps your stake whole');delete s.port.CSTK;
  const eq=s.px.MSFY,e0=eq.eps;eq.er=s.day;events();ok(eq.eps!==e0&&eq.er>s.day&&eq.last,'earnings report');
  const dk=STOCKS.find(k=>k.div),dq=s.px[dk.t];s.port[dk.t]={sh:1000,cost:1};const dc=s.cash,dp=dq.p;dq.nd=s.day;events();ok(s.cash>dc&&dq.p<dp&&dq.nd>s.day,'ex-dividend pays and drops the price');delete s.port[dk.t];
  newGame('Long','street');const ix0=idx();for(let d=0;d<365*40;d++){s.day=d;marketDay(1)}const ar=Math.log(idx()/ix0)/40;ok(ar>-.05&&ar<.19&&fear()>5&&fear()<200,'index returns '+(ar*100).toFixed(1)+'% a year');
  newGame('Pace','street');const sp0=speed,tb0=tab;speed=1;lastAct=-1e9;tab='dash';ok(paceNow()==='idle'&&PACE.idle===288,'idle: 5 seconds a day');lastAct=performance.now();ok(paceNow()==='active','playing slows time');
  s.day=nextTrading(s.day);s.min=600;tab='stock';ok(paceNow()==='trade','trading pace on Markets');s.min=1000;ok(paceNow()==='active','closed market, normal play pace');speed=2;ok(paceNow()==='fast','fast');speed=sp0;tab=tb0;lastAct=-1e9;
  s.min=480;const aw0=s.day,mk2=s.px.NOVA.k.at(-1);let sess=0;for(let d=aw0;d<aw0+32;d++)sess+=tradingDay(d)?1:0;let fin=false;catchUp(Math.floor(8*3600*AWAY),null,()=>fin=true);
  ok(fin&&s.day===aw0+32&&s.min===480&&s.px.NOVA.k.length-1-s.px.NOVA.k.indexOf(mk2)===sess,'8 hours away plays out a month, one bar per session');
  offline(8*36e5);ok(!catching&&$('#mbox').innerHTML.includes('While you were away'),'welcome-back summary');closeModal();
  newGame('Brk','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e6;const bq0=s.px.APEL;ACT.buy('APEL',10);
  bd['stock:APEL']={tp:bq0.p*.9};ACT.bset('stock:APEL');ok(!s.port.APEL.tp,'a take profit below the price is refused');
  ACT.bq('stock:APEL','sl:-.05');ACT.bq('stock:APEL','tp:.1');ok(s.port.APEL.sl<bq0.p&&s.port.APEL.tp>bq0.p,'take profit and stop loss set');
  shock('APEL',-.08,true);brackets();ok(!s.port.APEL&&s.log[0].t.startsWith('Stop loss'),'stop loss sells everything');
  ACT.buy('APEL',10);ACT.bq('stock:APEL','tp:.05');shock('APEL',.08,true);brackets();ok(!s.port.APEL&&s.log[0].t.startsWith('Take profit'),'take profit sells everything');
  ACT.buy('APEL',10);const ap=bq0.p;s.port.APEL.sl=ap*.9;s.port.APEL.tp=ap*1.2;bq0.op=ap*.8;bq0.lo=ap*.75;bq0.hi=ap*.85;const cash0=s.cash;brackets(1);ok(!s.port.APEL&&Math.abs(s.cash-cash0-10*ap*.8)<1e-6,'a gap through the stop fills at the open');
  ACT.xbuy('SATS','1000');const sc=coin('SATS');ACT.bq('coin:SATS','sl:-.05');ok(s.wallet.SATS.sl>0,'crypto stop loss set');sc.p*=.9;cbrackets();ok(!s.wallet.SATS,'crypto stop loss sells');
  ACT.buy('CSTK',10);s.port.CSTK.sl=500;s.port.CSTK.tp=2000;s.px.CSTK.p=2600;split(SK.CSTK);ok(s.port.CSTK.sl===50&&s.port.CSTK.tp===200,'splits move the levels too');sel='CSTK';tab='stock';ok(VIEWS.stock().includes('Take profit and stop loss'),'panel shows');
  newGame('Eco','street');s.eco.P=2;applyPrices();ok(BIZ[0].cost===240&&JOBS[0].pay===2*BASEP[0][0].pay&&ACTS.find(a=>a.c>0).c===2*BASEP[1][ACTS.findIndex(a=>a.c>0)].c,'prices follow the price level');s.eco.P=1;applyPrices();
  const hot=BM.hotel,lem=BM.lemon;s.eco.g=.4;const pfB=bizPf(hot);s.eco.g=-1;ok(pfB>1&&bizPf(hot)<0&&bizPf(lem)>.8,'a slump sinks hotels, barely touches lemonade');s.eco.g=.3;
  s.biz.cafe={n:5,mgr:0,pend:0,spent:1e5};closeCheck(BM.cafe,s.biz.cafe,1);ok(s.biz.cafe.n===4&&s.biz.cafe.spent===8e4,'competition closes a location');
  for(let y=0;y<15*365;y++){s.day++;ecoDay();marketDay(1)}const E=s.eco;ok([E.g,E.u,E.pi,E.r,E.lr,E.P].every(Number.isFinite)&&E.u>=.03&&E.u<=.14&&E.r>=0&&E.P>1.1&&E.P<3.5,'fifteen years of economy stay sane');
  s.cash=2e5;s.job='crew';relist();s.re.list[0]={...s.re.list[0],t:'studio'};const lu2=s.re.list[0].uid;ACT.pbuy(lu2,'m');const mp=s.props.find(p=>p.loan>0);ok(mp&&Math.abs(mp.rate-myRate())<1e-12,'a mortgage locks in the going rate for your credit');
  newGame('Bank','nerd');s.day=nextTrading(s.day);s.min=600;s.cash=1e6;const bk_F=s.fin;ACT.sdep('100000');const bk_sv0=bk_F.sav;finDay();ok(bk_F.sav>bk_sv0&&s.cash===9e5,'savings earn interest');
  ACT.fbuy('100000');ok(Math.abs(bk_F.fu*fundPx()-1e5)<1e-6,'index fund buys at a tenth of the index');const bk_nw0=netWorth();ok(bk_nw0>9.9e5&&bk_nw0<1.01e6,'bank money counts in net worth');ACT.fsell('all');ok(!bk_F.fu&&Math.abs(s.cash-9e5)<1,'sell the fund');
  ACT.bnd('10','100000');const bk_bd0=bk_F.bonds[0];ok(Math.abs(bondVal(bk_bd0)-1e5)<1,'a new bond is worth its price');s.eco.lr+=.02;ok(bondVal(bk_bd0)<9e4,'rising rates cut a long bond\'s price');const bk_cbond=s.cash;ACT.bndsell('0');ok(!bk_F.bonds.length&&s.cash-bk_cbond<9e4,'sell a bond early at the market price');
  s.job='admin';ACT.irapct('.06');const bk_ira0=bk_F.ira,bk_c0=s.cash;finDay();ok(bk_F.ira>bk_ira0&&Math.abs((bk_c0-s.cash)-jobPay()*.06)<1e-6&&Math.abs(iraVal()-jobPay()*.09)<1e-6,'retirement contributions with a 50% match');
  const bk_iv=iraVal(),bk_c1=s.cash;ACT.iraw('all');ok(bk_F.ira<1e-12&&Math.abs(s.cash-bk_c1-bk_iv*.9)<1e-6,'early withdrawal pays a 10% penalty');tab='bank';ok(VIEWS.bank().includes('Retirement account'),'bank screen');
  newGame('Tax','street');s.city='sun';const tx=(o)=>taxDue({...taxNew(),...o});ok(Math.abs(tx({ord:5e4})-4016)<.01,'income tax brackets');ok(Math.abs(tx({ord:5e4,lt:1e5})-19016)<.01,'long-term gains stack on income at 15%');
  ok(Math.abs(tx({ord:5e4})-tx({ord:5e4,st:-1e4})-360)<.01&&tx({ord:5e4,st:2e4,lt:-2e4})===tx({ord:5e4}),'losses offset gains, then $3,000 of income');
  s.cash=1e6;taxAdd('ord',5e4);ok(Math.abs(s.cash-(1e6-4016))<.01&&Math.abs(s.tax.paid-4016)<.01,'tax is taken as you earn');
  const tx0=s.tax.paid;capGain(1e4,s.day-100);ok(Math.abs(s.tax.st-1e4)<1e-9&&Math.abs(s.tax.paid-tx0-1200)<.01,'short-term gains taxed like income');capGain(1e4,s.day-400);ok(Math.abs(s.tax.lt-1e4)<1e-9,'long-term gains after a year');
  const cz2=s.cash;s.job='admin';iraPut(5e3);ok(Math.abs((s.cash-cz2)-5e3*.12)<.01,'retirement money comes off taxable income');
  const ty0=dateOf(s.day).y,tpaid=s.tax.paid;s.day+=365;taxAdd('ord',1);ok(s.tax.hist[ty0].tax===tpaid&&s.tax.paid===0,'a new tax year starts');
  s.cash=2e5;relist();s.re.list[0]={...s.re.list[0],t:'studio'};ACT.pbuy(s.re.list[0].uid);const hp2=s.props.at(-1);ACT.live(hp2.uid);hp2.paid=pval(hp2)*.5;const tp0=s.tax.paid;ACT.psell(hp2.uid);ok(s.tax.paid===tp0,'no tax on a home sold for under $250K of gain');
  tab='life';ok(VIEWS.life().includes('Taxes this year'),'tax summary');
  newGame('State','street');s.city='coast';s.cash=1e6;taxAdd('ord',5e4);ok(Math.abs((1e6-s.cash)-(4016+(5e4-14600*s.eco.P)*.08))<.01,'state income tax where you live');capGain(-2e4,s.day-10);s.cash=1e6;newGame('State2','street');s.cash=1e6;capGain(-1e4,s.day-10);ok(s.cash===1e6,'no state refund on a loss with no income');
  newGame('Trail','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e6;const tq=s.px.APEL;ACT.buy('APEL',10);ACT.btrail('stock:APEL','.1');const tr0=s.port.APEL.hw;
  shock('APEL',.2,true);brackets();ok(s.port.APEL&&s.port.APEL.hw>tr0*1.15,'a trailing stop follows the price up');shock('APEL',-.12,true);brackets();ok(!s.port.APEL&&s.log[0].t.startsWith('Stop loss'),'and sells on the way down');
  ACT.buy('APEL',10);ACT.btrail('stock:APEL','.1');const tw=s.port.APEL.hw;tq.op=tw*1.2;tq.hi=tw*1.3;tq.lo=tw*1.2;brackets(1);ok(s.port.APEL&&s.port.APEL.hw===tw*1.3,'fast simulation raises the trail on the day\'s high');tq.op=tw*1.25;tq.hi=tw*1.26;tq.lo=tw*1.1;brackets(1);ok(!s.port.APEL,'and sells when the low breaks it');
  ACT.xbuy('SATS','1000');ACT.btrail('coin:SATS','.05');const cs2=coin('SATS');cs2.p*=1.3;cbrackets();ok(s.wallet.SATS&&s.wallet.SATS.hw===cs2.p,'crypto trails too');cs2.p*=.9;cbrackets();ok(!s.wallet.SATS,'crypto trailing stop sells');
  const lp=s.px.MSFY.p;sel='MSFY';s.orders=[];ot={side:'buy',qty:10,type:'limit',px:+(lp*1.2).toPrecision(5),tp:+(lp*1.5).toPrecision(5),sl:+(lp*.8).toPrecision(5),tif:'day'};ACT.order();const ob=s.orders[0];ok(ob&&ob.tp&&ob.sl,'a limit buy can carry a take profit and stop loss');
  minute();ok(!s.orders.length&&s.port.MSFY?.tp===ob.tp&&s.port.MSFY?.sl===ob.sl,'they switch on when it fills');ot={side:'buy',qty:10,type:'market'};
  newGame('Mar','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e4;const mg_n=Math.floor(1.8e4/s.px.APEL.p);ok(!canBuy('APEL',mg_n,false)&&canBuy('APEL',mg_n,true)&&!canBuy('APEL',mg_n*2,true),'margin doubles buying power, and no more');
  ACT.buy('APEL',mg_n,true);ok(s.port.APEL.sh===mg_n&&s.mloan>7e3&&s.cash<1,'bought on margin');const mg_l=s.mloan;shortDay();ok(s.mloan>mg_l,'margin interest');
  shock('APEL',-.6,true);marginCheck();const mg_a=acct();ok((mg_a.eq>=mg_a.maint-1e-6||!s.port.APEL&&s.mloan===0)&&s.log.some(l=>l.t.startsWith('Margin call')),'a margin call sells you back above the minimum, or out entirely');
  newGame('Short','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e5;const nw_s=netWorth();ACT.short('NVBA','100');ok(s.shorts.NVBA?.sh===100&&s.cash>1e5&&Math.abs(netWorth()-nw_s)<nw_s*.01,'shorting adds cash and an equal debt');
  shock('NVBA',-.1,true);const cs_s=s.cash;ACT.cover('NVBA','all');ok(!s.shorts.NVBA&&s.cash>1e5,'a short profits when the price falls');
  ACT.short('NVBA','10000');ok(!s.shorts.NVBA,'too big a short is refused');const pz2=PENNIES[3];s.px[pz2.t].p=.5;ACT.short(pz2.t,'100');ok(!s.shorts[pz2.t],'no shorting penny stocks under $1');
  const dk2=STOCKS.find(k=>k.div&&!k.pn);ACT.short(dk2.t,'10');const cd2=s.cash;s.px[dk2.t].nd=s.day;events();ok(s.cash<cd2,'shorts owe the dividend');ACT.cover(dk2.t,'all');
  const pz3=PENNIES[4];s.px[pz3.t].p=2;ACT.short(pz3.t,'100');ok(s.shorts[pz3.t],'penny short above $1');const cs3=s.cash;bankrupt(pz3);ok(!s.shorts[pz3.t]&&s.cash<=cs3,'bankruptcy closes a short at a profit');
  sel='NVBA';ot={side:'short',qty:10};tab='stock';ok(VIEWS.stock().includes('Short'),'short ticket');ot={side:'buy',qty:10,type:'market'};
  newGame('Opt','street');s.day=nextTrading(s.day);s.min=600;s.cash=1e6;const ok_k=SK.MSFY,ok_S=s.px.MSFY.p,ok_x=optExpiries(),ok_K=optStrikes(ok_S)[4],ok_T=optT(ok_x[0]);
  ok(ok_x.length===3&&ok_x.every(d=>tradingDay(d)&&wdOf(d)<=4),'three monthly expiries');const ok_c=bs(ok_k,'call',ok_K,ok_x[0]),ok_p=bs(ok_k,'put',ok_K,ok_x[0]);
  ok(Math.abs((ok_c.px-ok_p.px)-(ok_S*Math.exp(-(ok_k.div||0)*ok_T)-ok_K*Math.exp(-s.eco.r*ok_T)))<1e-6,'put-call parity');ok(ok_c.delta>0&&ok_c.delta<1&&ok_p.delta<0&&ok_p.delta>-1,'deltas');
  const ok_h=s.mkt.h;s.mkt.h*=4;ok(bs(ok_k,'call',ok_K,ok_x[0]).px>ok_c.px,'fear makes options dearer');s.mkt.h=ok_h;const ok_er=s.px.MSFY.er;s.px.MSFY.er=ok_x[0]+30;const ok_c0=bs(ok_k,'call',ok_K,ok_x[0]).px;s.px.MSFY.er=ok_x[0]-1;ok(bs(ok_k,'call',ok_K,ok_x[0]).px>ok_c0,'earnings before expiry are priced in');s.px.MSFY.er=ok_er;
  sel='MSFY';oq=1;oxp=ok_x[0];const ok_c1=s.cash;ACT.obuy(`call|${ok_K}|${ok_x[0]}`);ok(s.opts.length===1&&s.cash<ok_c1,'buy a call');ok(Math.abs(netWorth()-(ok_c1-(s.opts[0].cost-optVal())))<1,'options count in net worth');
  shock('MSFY',.15,true);const ok_c2=s.cash;ACT.osell(String(s.opts[0].id));ok(!s.opts.length&&s.cash-ok_c2>0,'sell a call after a rally');
  ACT.obuy(`call|${ok_K}|${ok_x[0]}`);ACT.obuy(`put|${ok_K}|${ok_x[0]}`);for(const o of s.opts)o.exp=s.day;s.px.MSFY.p=ok_K*1.1;const ok_c3=s.cash;optSettle();ok(!s.opts.length&&Math.abs(s.cash-ok_c3-ok_K*.1*100)<1e-6,'at expiry the call pays its intrinsic value and the put expires worthless');
  tab='stock';vmode='options';ok(VIEWS.stock().includes('Strike'),'options chain');vmode='chart';
  newGame('Board','street');const lb0=[lb,lbRows,lbMe];lb={};lbMe='u_me';lbRows=[{id:'u_x',fam:'<img src=x onerror=alert(1)>',gen:3,nw:2e6,goals:5},{id:'u_me',fam:'Board',gen:1,nw:1e5,goals:1},{id:'u_bad',fam:'Bad',gen:'x',nw:'NaN'}];
  const lbh=lbHtml();ok(lbh.includes('&lt;img')&&!lbh.includes('<img src=x')&&lbh.includes('(you)')&&!lbh.includes('Bad</b>'),'leaderboard escapes and filters other players\' rows');[lb,lbRows,lbMe]=lb0;ok(lbHtml()==='','no leaderboard off the published page');
  newGame('Goal','street');s.cash=2e6;checkGoals();ok(s.goals.nw1&&s.goals.nw2&&!s.goals.nw3,'goals unlock');const gn=Object.keys(s.goals).length;checkGoals();ok(Object.keys(s.goals).length===gn,'goals unlock once');delete s.goals;upgrade();ok(s.goals.nw2&&s.log[0].t.includes('already reached'),'old saves backfill goals quietly');
  const lf_s=s;newGame('Life','street');s.cash=1e6;const lf_P=s.eco.P;
  ok(s.pets.length===0&&s.ins==='basic'&&insPrem()===0,'free basic insurance with a job');
  const lf_c=s.cash,lf_o=billMed(1e4*lf_P);ok(Math.abs(lf_o-(3000+7000*.3)*lf_P)<1e-6&&Math.abs(s.cash-(lf_c-lf_o))<1e-6,'deductible, then 70% covered');
  billMed(1e5);ok(Math.abs(s.med.oop-8000*lf_P)<1e-6,'out-of-pocket cap');s.ins='none';ok(oopOf(500).out===500,'uninsured pays in full');s.ins='basic';
  const lf_ca=addCond('cancer');ok(lf_ca.hid&&!VIEWS.health().includes('Stage 1'),'cancer starts hidden');ACT.act('doc');ok(!lf_ca.hid&&VIEWS.health().includes('Stage 1 cancer'),'a check-up finds it');
  ACT.treat('cancer');ok(lf_ca.tx===s.day+90,'treatment starts');const lf_cu=CSTAGE.cure[0];CSTAGE.cure[0]=1;s.day=lf_ca.tx;healthDay(30);CSTAGE.cure[0]=lf_cu;ok(!cond('cancer'),'treatment cures');
  const lf_dp=addCond('dep');ACT.treat('dep');ok(lf_dp.tx===1&&medDaily()>0&&lifeCost()>insPrem(),'therapy costs every day');ACT.untreat('dep');s.conds=[];
  const lf_h=addCond('heart');lf_h.tx=0;ok(condHaz(lf_h)===.08,'untreated heart disease is deadly');ACT.treat('heart');ok(lf_h.tx===1&&condHaz(lf_h)===.01,'surgery cuts the risk');s.conds=[];
  const lf_fl=addCond('flu');ACT.treat('flu');ok(lf_fl.left<=2,'a doctor shortens the flu');s.conds=[];
  const lf_k=openCase('dui');ok(needs().some(n=>n.k==='case')&&VIEWS.life().includes('Drunk-driving'),'cases show up');const lf_c2=s.cash;ACT.case(String(lf_k.id),'plead');
  ok(!s.legal.cases.length&&s.legal.rec.length===1&&Math.abs(lf_c2-s.cash-2500*lf_P*.6)<1e-6&&jailed(),'a guilty plea: fine, record, a day inside');
  ok(jobMiss(JM.police).includes('a clean record')&&!jobMiss(JM.crew).includes('a clean record'),'a record rules out some jobs');
  const lf_bt=document.createElement('button');lf_bt.dataset.a='gig';document.body.append(lf_bt);const lf_c3=s.cash;lf_bt.click();lf_bt.remove();ok(s.cash===lf_c3,'jail blocks gigs');
  ok(flows().job===0&&lifeLine().includes('in jail'),'no salary in jail');
  const lf_sc=openCase('sec',4e4);ACT.case(String(lf_sc.id),'plead');ok(!s.job&&s.legal.jail-s.day>=30,'a long sentence costs you your job');
  s.legal.jail=0;const lf_nb=openCase('nbr',1e4);for(let i=0;i<31;i++)day();ok(!s.legal.cases.includes(lf_nb),'an ignored case goes to trial');
  const lf_sm=s.st.sma;ACT.hob('chess');ok(hobSk('chess')>3&&s.st.sma>lf_sm,'chess practice');const lf_s1=hobSk('chess');ACT.hob('chess');ok(hobSk('chess')===lf_s1,'practice cooldown');
  s.hob.code={sk:60,last:s.day,n:1};const lf_c4=s.cash;ACT.hshow('code');ok(s.cash>lf_c4,'freelance pays');
  s.hob.write={sk:80,last:s.day,n:1};ACT.hshow('write');ok(s.roy?.v>0,'a book pays royalties');
  s.hob.cook={sk:100,last:s.day,n:1};ok(lifeCost()<insPrem()+medDaily(),'cooking cuts groceries');
  s.hob.music={sk:50,last:s.day-100,n:1};lifeDay(30);ok(hobSk('music')<50,'unused skills fade');
  ACT.adopt('dog');ok(s.pets.length===1&&petSum('hap')>0&&VIEWS.hobby().includes(s.pets[0].n),'adopt a dog');s.pets[0].dies=s.day;petsDay();ok(!s.pets.length,'pets pass on');
  newGame('Old','street');delete s.pets;s.pet=1;upgrade();ok(s.pets.length===1&&s.pets[0].t==='cat'&&!('pet' in s),'old cats come along');
  s.cash=1e6;meet('friend',60);ACT.bbuy('lemon','1');for(const e of EV2){for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}}
  for(const k in LATER)LATER[k]({u:s.people[0].uid,v:1000});
  tab='health';VIEWS.health();tab='hobby';VIEWS.hobby();s=lf_s;
  const kq_s0=s;newGame('Kid','nerd');meet('spouse',80);const kq=addChild();ok(kq.k&&kq.k.tr.length===2&&kq.k.gs>0,'kids have traits and genes');
  kq.b=s.day-10*365;const kq_s=kq.k.sma;s.cash=1e5;ACT.pp(String(kq.uid),'tutor');ok(kq.k.sma>kq_s,'a tutor helps');
  ACT.pp(String(kq.uid),'school');ok(kq.k.sch==='private'&&kidsCost()>0&&VIEWS.people().includes('Private school'),'private school');
  s.cash=1e5;ACT.pp(String(kq.uid),'fund');ok(kq.k.fund===5000,'college fund');ACT.pp(String(kq.uid),'fund');ok(kq.k.fund===5000,'fund cooldown');
  kq.k.sma=70;kq.b=s.day-18*365;peopleDay();ok(kq.out&&kq.k.path==='college'&&kq.k.fund<1&&kq.k.loan>0,'off to college, fund first');
  ok(!personRow(kq).includes('Hire a tutor'),'no tutoring adults');
  s.day=kq.k.grad;kidDay(kq);ok(kq.k.path==='colleged'&&JM[kq.k.job],'graduates into a job');
  kq.k.sp='Zed';kq.k.gk=[{n:'Tiny',b:s.day-2*365}];kq.k.fund=777;addPet('parrot');
  const kh=heirOf(kq);ok(kh.ks.sma===kq.k.sma&&kh.degs[0].p==='ba'&&kh.job===kq.k.job&&kh.fam.some(p=>p.role==='spouse'&&p.n==='Zed')&&kh.fam.some(p=>p.role==='child'&&p.n==='Tiny')&&kh.pets.length===1,'the heir is who the kid became');
  newGame(kq.n,'heir',kh);ok(s.edu===2&&s.job===kh.job&&partner()?.n==='Zed'&&kids()[0]?.k&&Math.floor(ageOf(kids()[0]))===2&&s.tr.join()===kh.tr.join()&&s.pets[0].t==='parrot','heir starts with their life');
  ok(Math.abs(s.cash-kh.inherit-777)<1&&s.debt===kh.loan,'fund and loans carry over');
  ok(estateTax(1e7*s.eco.P)===0&&Math.abs(estateTax(23e6*s.eco.P)-4e6*s.eco.P)<1,'estate tax');
  startModal(heirOf(kids()[0]));ok($('#mbox').innerHTML.includes('Grew up'),'heir modal shows the upbringing');$('#modal').hidden=true;
  newGame('Kids2','street');meet('spouse',70);const kq2=[addChild(),addChild(),addChild()];kq2[0].b=s.day-8*365;kq2[1].b=s.day-14*365;kq2[2].b=s.day-16.5*365;s.cash=1e6;
  for(const e of EV3)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}
  kq2[1].b=s.day-30*365;for(const e of EV3.filter(e=>e.id==='kask'))ok(e.c(s),'adult kids ask for help');
  for(let i=0;i<400;i++)day();ok(kids().every(k=>Number.isFinite(k.k.sma)),'kids grow');s=kq_s0;
  const cq_s0=s;newGame('Crew','street');day();ok(boss()&&mates().length>=2&&BOSSES[boss().bt],'jobs come with a team');
  tab='work';ok(VIEWS.work().includes('Your team')&&VIEWS.people().includes('Coworker'),'the team shows up');
  const cq_b=boss();cq_b.rel=100;ok(promoNeed()===45,'a boss who likes you lowers the bar');cq_b.rel=50;ACT.pp(String(cq_b.uid),'lunch');ok(cq_b.rel>50,'lunch with the boss');
  const cq_m=mates()[0];cq_m.rel=70;fire();day();ok(!boss()&&!mates().length&&s.people.some(p=>p.uid===cq_m.uid&&p.role==='friend'),'the team stays behind, close coworkers become friends');
  s.job='crew';day();ok(boss(),'a new job brings a new team');
  s.fl.next=0;day();ok(s.fl.offers.length>0,'freelance offers');ACT.flt(String(s.fl.offers[0].id));ok(s.fl.jobs.length===1,'take a contract');if(s.fl.offers[0])ACT.flt(String(s.fl.offers[0].id));ok(s.fl.jobs.length===1,'one contract while employed');
  const cq_c=s.cash,cq_x=xpY(s.fl.jobs[0].fld);s.fl.jobs[0].left=1;flDay();ok(!s.fl.jobs.length&&s.cash>cq_c&&xpY(FLT.find(t=>t.n===s.log[0].t.match(/<b>(.*?)<\/b>/)?.[1])?.fld||'delivery')>=0,'contracts pay when done');
  s.cash=1e6;ACT.found('saas');ok($('#mbox').innerHTML.includes('Found it')&&!s.su,'founding asks first');ACT.found('saas','yes');ok(s.su&&!s.job&&s.su.cash===2.5e5*s.eco.P**0&&flCap()===0,'founded');
  ACT.apply('crew');ok(!s.job&&$('#modal').hidden,'no interviews while founding');ACT.suhire();ok(s.su.hires===1&&suRunway(s.su)>0,'hire');ok(Math.abs(netWorth()-(s.cash+suWorth()+walletVal()+finVal()))<1e6,'startup counts toward net worth');
  s.su.offer={pre:8e6,raise:2e6,d:s.day};ACT.suraise();ok(s.su.st===1&&Math.abs(s.su.own-.8)<1e-9&&s.su.val===1e7,'a round dilutes you');
  tab='work';ok(VIEWS.work().includes('Founder of'),'founder screen');s.su.acq={v:5e7,d:s.day};ok(needs().some(n=>n.k==='su'),'offers need you');
  const cq_c2=s.cash;ACT.suacq();checkGoals();ok(!s.su&&s.cash-cq_c2>2e7&&s.goals.exit,'sell the company');
  ACT.found('ai','yes');s.su.st=4;s.su.hires=90;s.su.prog=1e4;s.su.cash=1e8;s.su.retry=0;suDay();ok(s.su&&s.su.prog<=SUST[5].at,'no IPO without a big enough team');s.su.hires=180;s.su.prog=1e4;suDay();ok(!s.su&&s.car2.ipo===1&&s.later.some(p=>p.id==='lockup'),'an IPO with a lockup');const cq_c3=s.cash;LATER.lockup(s.later.find(p=>p.id==='lockup'));ok(s.cash>cq_c3,'the lockup ends');
  s.cash=1e6;ACT.found('food','yes');s.su.cash=-1;suDay();ok(!s.su,'out of money, out of business');
  ACT.found('app','yes');ACT.sukill('yes');ok(!s.su,'shut it down');
  s.job='crew';day();s.cash=1e6;for(const e of EV4)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}
  LATER.ethics();s=cq_s0;
  const lg_s0=s;newGame('Tree','nerd');tab='legacy';ok(VIEWS.legacy().includes('The family of Tree'),'family tree');
  die();ok(s.tree.length===1&&s.tree[0].cause,'a death is recorded');$('#modal').hidden=true;
  newGame('Tree Jr.','street',heirOf(null));ok(s.tree.length===1&&VIEWS.legacy().includes('Tree Jr.')&&VIEWS.legacy().includes('2 generations'),'the tree carries over');
  taxRoll();s.tax.ord=1e5;s.cash=1e5;const lg_c=s.cash,lg_d=donate(1e4);ok(lg_d===1e4&&s.given===1e4&&s.cash>lg_c-1e4,'donations are deductible');
  s.cash=1e6;ok(Math.abs(donate(1e5)-5e4)<1e-6,'the deduction caps at 60% of income');
  s.cash=2e6;ACT.give(String(1e6),'fdn');ok(s.fdn===1e6,'a foundation');const lg_g=s.given;fdnDay();ok(s.given>lg_g&&heirOf(null).fdn>0,'the foundation grants, and passes on');
  newGame('Prop','rich');s.cash=5e6;s.re.list[0].cond=40;const lg_l=s.re.list[0];ok(lval(lg_l)<PM[lg_l.t].base*lg_l.m*s.re.idx*.9,'fixer-uppers sell cheap');ACT.pbuy(String(lg_l.uid));const lg_p=s.props.at(-1);ok(lg_p.cond===40,'bought a fixer-upper');
  const lg_rc=renoCost(lg_p),lg_v0=pval(lg_p);ACT.reno(String(lg_p.uid));ok(lg_p.reno&&rentOf(lg_p)===0,'renovating');s.day=lg_p.reno;propDay();ok(lg_p.cond===100&&lg_p.rv&&pval(lg_p)-lg_v0>lg_rc,'a renovation adds more than it costs');
  tab='home';ok(VIEWS.home().includes('Condition'),'condition column');
  const lg_l2=s.re.list[1];ACT.pbuy(String(lg_l2.uid));const lg_p2=s.props.at(-1);lg_p2.from=0;ok(renting(lg_p2),'a rental');
  for(const e of EV5)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}
  s.world={id:'pandemic',end:s.day+10};ok(worldBiz(BM.cafe)<1&&worldBiz(BM.app)>1&&CONDS.flu.r(30)>3,'a pandemic empties cafes and spreads flu');s.day+=11;worldDay();ok(!s.world,'the pandemic ends');
  for(let i=0;i<365*80;i++){s.day++;worldDay()}ok(Number.isFinite(s.eco.g),'decades of world events');s=lg_s0;
  const lv_s0=s;newGame('Love','nerd');const lv_p=meet('date',70);ok(lv_p.pt&&PERS[lv_p.pt]&&lv_p.gs,'partners have a personality');
  s.cash=1e6;married(lv_p);ok(lv_p.role==='spouse'&&lv_p.wedNW>0&&s.inbox.some(i=>i.id==='wedding'),'a wedding to plan');ACT.pick('wedding','1');ok(!s.inbox.some(i=>i.id==='wedding'),'the wedding happened');
  lv_p.job='swe';ok(spouseInc()>0&&flows().job>=spouseInc()&&VIEWS.people().includes(PERS[lv_p.pt].n),'a working spouse adds to the household');
  s.cash=3e6;const lv_d=divCost(lv_p);ok(lv_d>=Math.round((netWorth()-lv_p.wedNW)*.5),'divorce splits what you built');lv_p.pre=1;ok(divCost(lv_p)<lv_d,'a prenup protects what you brought');
  for(const e of EV6){if(!partner())married(meet('date',60));if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}}
  s.cash=1000;s.fin.sav=5000;s.fin.fu=100;s.fin.fc=100*fundPx();s.fin.fd=s.day-400;const lv_fu=s.fin.fu;payOut(8000);ok(Math.abs(s.cash)<1e-6&&s.fin.sav===0&&Math.abs((lv_fu-s.fin.fu)*fundPx()-2000)<1e-6,'big bills draw on savings, then the fund');
  checkGoals();s=lv_s0;
  const cy_s0=s;newGame('City','nerd');const cy_p=jobPay();s.city='metro';ok(Math.abs(jobPay()-cy_p*1.3)<1e-6,'big-city pay');s.city='suburb';
  s.cash=1e5;ACT.move('town');ok(s.city==='town'&&s.cash<1e5&&s.re.list.every(l=>l.city==='town'),'moving to a small town');tab='home';ok(VIEWS.home().includes('Where you live'),'city picker');
  s.wage=35*365*200*s.eco.P;s.startAge=SS_AGE;oldDay(age());ok(s.ss>0&&s.pension>=s.ss,'Social Security at 67');s.startAge=80;s.st.hea=20;ok(careCost()>0&&lifeCost()>=careCost(),'care costs in old age');
  ok(heirOf(null).city==='town','the heir stays in town');s=cy_s0;
  const po_s0=s;newGame('Pol','nerd');s.fol=1e4;s.startAge=30;s.cash=1e6;ok(!polMiss(OM.council).length&&polMiss(OM.mayor).length,'council first');
  ACT.run('council');ok(s.pol.camp&&s.cash<1e6,'a campaign');s.pol.camp.odds=1;s.day=s.pol.camp.end;polDay();ok(s.pol.cur==='council'&&s.pol.held.council===1&&s.job,'a part-time seat, and you keep your job');
  ok(polPay()>0&&flows().job>=polPay(),'office pays');tab='office';ok(VIEWS.office().includes('Approval'),'politics screen');
  s.fol=1e5;ACT.run('mayor');s.pol.camp.odds=1;s.day=s.pol.camp.end;polDay();ok(s.pol.cur==='mayor'&&!s.job,'mayor is full time');ACT.apply('crew');ok(!s.job,'no day job as mayor');
  s.day=s.pol.until;polDay();ok(s.inbox.some(i=>i.id==='rerun'),'a re-election decision');
  for(const e of EV7)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}
  s.cash=1e8;s.club=null;ACT.tbuy('minor');ok(s.club&&VIEWS.shop().includes('Minor-league'),'own a team');ACT.tpay('1.6');ok(s.club.pay===1.6,'payroll');
  const po_c=s.cash;let po_d=dayOf(dateOf(s.day).y,9,1);if(po_d<=s.day)po_d=dayOf(dateOf(s.day).y+1,9,1);s.day=po_d;clubDay();ok(s.club.season===dateOf(s.day).y&&s.cash!==po_c,'a season settles');
  ACT.tsell();ok(!s.club,'sell the team');s.cars=[{uid:1,t:'hatch',v:9000,paid:9000,bought:0}];const po_g=gig();s.cars=[];ok(po_g>gig(),'rideshare pays more');s=po_s0;
  const cr_s0=s;newGame('Cred','nerd');ok(credit()===650&&creditWord(650)==='Fair','credit starts fair');
  s.cash=-100;const cr0=s.credit;creditDay();ok(s.credit<cr0,'missed payments hurt');s.credit=600;ok(!canBorrow(1e5),'no mortgage under 620');s.credit=800;ok(myRate()===mrate(),'great credit gets the base rate');s.credit=540;ok(myRate()>mrate()+.019&&debtAPR()>.2,'bad credit costs more');
  tab='bank';ok(VIEWS.bank().includes('Credit score'),'credit on the bank screen');s.cash=-5e4;ACT.bankrupt('yes');ok(s.cash===0&&s.credit===380&&s.bk>s.day,'bankruptcy');
  s.cash=1e5;for(let i=0;i<20;i++){s.cd.out=0;ACT.act('out')}ok(vice('alc')>60,'drinking adds up');viceDay();tab='health';ok(VIEWS.health().includes('Go to rehab'),'rehab offered');s.job='admin';ACT.rehab();ok(vice('alc')===0&&s.rehab>s.day&&flows().job===0,'rehab: clean, and no pay for a month');
  s.cash=1e8;s.cd={};ACT.travel('safari');ok(cdLeft('t_safari')>0&&s.cash<1e8,'a safari');ACT.travel('space');ok(s.cd.t_space,'to space');tab='life';ok(VIEWS.life().includes('Travel'),'travel section');
  s.job='army';s.rank=2;ok(jobTitle()==='Sergeant','army ranks');s.jobDays=VET;milDay();ok(isVet()&&tuition(PG.ba,{cost:1})===0,'the GI Bill');ACT.ins('va');ok(s.ins==='va','VA healthcare');
  for(const e of EV8)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}
  s=cr_s0;
  const st_s0=s;newGame('Story','nerd');ok(s.mile.length===1&&s.mile[0].t.includes('Turned 18'),'a life story starts');for(let i=0;i<70;i++)day();married(meet('date',70));addChild();tab='life';ok(s.sth.length>=2&&VIEWS.life().includes('Your life so far')&&VIEWS.life().includes('Married'),'the story and the stats chart');
  die();$('#modal').hidden=true;newGame('Story Jr.','street',heirOf(null));tab='legacy';ok(VIEWS.legacy().includes('Their story'),'past lives keep their story');s=st_s0;
  const tp_s0=s;newGame('Tips','rich');s.job=null;ok(tips().some(x=>x.k==='job')&&VIEWS.dash().includes('Next steps'),'next steps on Home');s.ins='none';s.job='crew';ok(tips().length<=3,'at most three');s=tp_s0;
  const bz_s0=s;newGame('Biz','rich');s.cash=1e6;ACT.bbuy('truck','3');const bz_o=s.biz.truck;ok(bizVal(BM.truck,bz_o)>0&&Math.abs(netWorth()-(s.cash+bizWorth()+finVal()+walletVal()))<1,'businesses are worth a multiple of profit');
  ACT.mgr('truck');bz_o.n=25;const bz_v=bizVal(BM.truck,bz_o);s.cash=1e7;ACT.bfr('truck');ok(bz_o.fr&&bizVal(BM.truck,bz_o)>bz_v,'franchising lifts value');
  const bz_c=s.cash;ACT.bsell('truck');ok(!$('#modal').hidden&&s.biz.truck,'selling asks first');ACT.bsell('truck','yes');ok(!s.biz.truck&&s.cash>bz_c,'sold the chain');
  meet('spouse',60).b=s.day-30*365+355;for(const e of EV9)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}s=bz_s0;
  const e10_s0=s;newGame('Ev','rich');s.cash=1e6;s.cars=[{uid:uid(),t:'hatch',v:9000,paid:9000,bought:0}];meet('sibling',60);s.re.list[0].t='studio';ACT.pbuy(String(s.re.list[0].uid));for(const e of EV10)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}s=e10_s0;
  const ls_s0=s;newGame('Style','nerd');const ls_p=jobPay();ACT.hours('part');ok(Math.abs(jobPay()-ls_p*.55)<1e-6,'part time pays about half');ACT.hours('over');ok(jobPay()>ls_p,'overtime pays more');ACT.diet('chef');ok(dietCost()>0&&lifeCost()>=dietCost(),'a private chef costs money');s.diet='normal';const ls_r=CONDS.diab.r(50);ACT.diet('cheap');ok(dietCost()<0&&CONDS.diab.r(50)>ls_r,'cheap food saves money and raises risk');tab='life';ok(VIEWS.life().includes('How you live'),'lifestyle choices on Life');s=ls_s0;
  const op_s0=s;newGame('Opt','nerd');ACT.setopt('dec','7');ok(decDays()===7,'decisions wait 7 days');s.inbox=[{id:'lotto',d:s.day,a:0}];for(let i=0;i<8;i++)day();ok(!s.inbox.some(i=>i.id==='lotto'),'and then decide themselves');ACT.setopt('pause');speed=1;s.inbox=[];newEvent();ok(speed===0,'pause on a new decision');speed=0;ACT.setopt('quiet');ok(opt('quiet'),'quiet mode');$('#modal').hidden=true;s=op_s0;
  const hb_s0=s;newGame('House','rich');s.world={id:'housing',start:s.day,end:s.day+1000};ok(housingDrift()>0,'a housing boom');s.day+=700;ok(housingDrift()<0&&s.world.bust,'then the bust');s.world=null;const hb_p=addPet('dog');ok(petPlay(hb_p.uid)&&!petPlay(hb_p.uid),'walk the dog, once every few days');for(const e of EV11)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}s=hb_s0;
  const tr_s0=s;newGame('Trust','rich');s.cash=3e7;ACT.trust(String(1e7));ok(s.trust.v===1e7&&exemptLeft()===3e6*s.eco.P&&s.cash===2e7,'a trust gift inside the exemption is tax-free');ACT.trust(String(5e6));ok(s.trust.v===1.5e7&&Math.abs(s.cash-(2e7-5e6-2e6*.4))<1,'beyond the exemption, 40% gift tax');
  trustDay();ok(s.trust.v>1.5e7,'the trust grows');const tr_h=heirOf(null);ok(tr_h.trust>0&&tr_h.inherit>=tr_h.trust,'the trust passes to the heir');tab='legacy';ok(VIEWS.legacy().includes('Family trust'),'trust on the family tree');
  const tr_f=meet('friend',80);ACT.pp(String(tr_f.uid),'bff');ok(s.best===tr_f.uid&&VIEWS.people().includes('Best friend'),'a best friend');
  s.startAge=70;s.cash=1e6;s.re.list[0].t='studio';ACT.pbuy(String(s.re.list[0].uid));ACT.comm();ok(s.rc&&!homeP()&&rentNow()===commFee()&&lifeLine().includes('retirement community'),'a retirement community');
  for(const e of EV12)if(!e.c||e.c(s))for(const c of e.ch){const a=e.a?e.a(s):0;e.d(s,a);ok(typeof c[1](s,a)==='string','event '+e.id)}s=tr_s0;
  const sl_s0=s;newGame('Let','rich');s.cash=5e6;ACT.pbuy(String(s.re.list[0].uid));ACT.pbuy(String(s.re.list[1].uid));const sl_p=s.props.find(p=>p.uid!==s.home);sl_p.from=0;const sl_r=rentOf(sl_p);ACT.stl(String(sl_p.uid));ok(sl_p.stl&&rentOf(sl_p)>sl_r,'a holiday let pays more');tab='home';ok(VIEWS.home().includes('Holiday let'),'holiday let shown');
  ACT.chstart();ok(s.ch.on,'a channel');const sl_c=chPost();ok(sl_c&&s.ch.subs>0&&!chPost(),'post an episode, then wait');ok(chInc()>0,'ads pay');tab='chirp';ok(VIEWS.chirp().includes('Your channel'),'channel on Chirp');
  s.study={p:'ba',sc:'state',mj:'Business',left:300,days:1095,g:60};ACT.abroad();ok(s.study.abroad,'a semester abroad');s=sl_s0;
  tab='dash';ok(VIEWS.dash().includes('Goals'),'goals on home');goalsModal();
  const sp2=meet('spouse',70),k1=addChild(),k2=addChild(),k3=addChild();k1.b=s.day-40*365;k2.b=s.day-30*365;k3.b=s.day-5*365;k1.rel=90;
  deathModal();ok($('#mbox').innerHTML.includes('Continue as '+k1.n),'death lists the kids');ACT.heir(String(k1.uid));
  ok(heir.kid===k1.n&&Math.floor(heir.age)===40&&heir.fam.length===3,'heir from a kid');newGame(k1.n,'street',heir);
  ok(s.gen===2&&Math.floor(age())===40&&s.goals.nw2&&s.people.some(p=>p.role==='parent'&&p.n===sp2.n)&&s.people.filter(p=>p.role==='sibling').map(p=>Math.floor(ageOf(p))).sort((a,b)=>a-b).join()==='5,30','heir keeps family and goals');
  newGame('Young','street');const y1=addChild(),y2=addChild();y1.b=-5*365;y2.b=-2*365;const hy=heirOf(y1);ok(Math.round(hy.age)===18&&Math.round(-hy.fam[0].b/365)===15,'a young heir comes of age');
  newGame('Solo','street');ACT.heir();ok(!heir.kid&&!heir.fam&&heir.gen===2,'no kids, a relative inherits');$('#modal').hidden=true;
  newGame('Sim','rich');let d=0;for(;d<40000&&!s.dead;d++){day();if(d%7===0){s.inbox=[];ACT.colAll()}}
  const vals=[s.cash,netWorth(),s.fol,...Object.values(s.st),...Object.values(s.px).map(q=>q.p),...s.cx.coins.map(c=>c.p),walletVal()];
  ok(vals.every(Number.isFinite),'finite after sim');ok(s.dead,'eventually dies');
  console.log(`self-test passed · simulated ${d} days, died at ${Math.floor(age())}`);
  const snap=JSON.parse(JSON.stringify(s));packSave(snap).then(unpackSave).then(x=>console.log(JSON.stringify(x)===JSON.stringify(snap)?'save backup round trip ok':'save backup round trip FAILED'),e=>console.log('save backup round trip FAILED '+e));
}
